(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"SB_wedding_160x600_atlas_1", frames: [[0,0,303,320],[0,322,63,53],[305,0,160,600]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_24 = function() {
	this.initialize(ss["SB_wedding_160x600_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.logowhite2x = function() {
	this.initialize(ss["SB_wedding_160x600_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.wedding_160x6001x = function() {
	this.initialize(ss["SB_wedding_160x600_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.TAG = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFgBfQgPgPAAgZIAAgOIAkAAIAAAMQAAAYAWAAQAUAAAAgVQAAgMgIgKQgGgJgSgNQgsgfAAghQAAgYAOgQQAQgRAcAAQAYAAAPAQQAPAPAAAXIAAAOIgjAAIAAgNQAAgWgUAAQgTAAAAATQAAAMAIAKQAHAIASAOQAVAOALAOQAMARgBAUQABAZgRAQQgQARgZAAQgcAAgQgPgABPBfQgSgPABgYIAAigIAnAAIAACgQAAAUATAAQAVAAgBgUIAAigIAnAAIAACgQAAAYgQAPQgRAPgaAAQgZAAgQgPgAhABdQgRgPABgaIAAhnQgBgaARgPQAQgRAbAAQAaAAAQARQAQAPAAAaIAABnQAAAagQAPQgQARgaAAQgbAAgQgRgAgpg2IAABtQAAAUAUAAQAUAAAAgUIAAhtQAAgUgUAAQgUAAAAAUgAqiBfQgRgPAAgYIAAigIAnAAIAACgQAAAUATAAQAVAAAAgUIAAigIAmAAIAACgQgBAYgQAPQgQAPgaAAQgZAAgQgPgAEuBqQgWAAABgfIAAgnQgBgSgQAAIgUAAIAABXIgnAAIAAjRIBBAAQAVAAANAMQANAMAAAWIAAAdQABAZgYAHQAMADAGAJQAGAJAAAKIAAAnQAAANAIAIIAAAMgAD0gKIAUAAQAQAAAAgRIAAgeQgBgPgOAAIgVAAgALGBpIAAjRIBiAAIAAAhIg7AAIAAA3IArAAIAAAgIgrAAIAABZgAJTBpIAAjRIAnAAIAACuIA7AAIAAAjgAHaBpIAAjRIBkAAIAAAiIg9AAIAAA0IAqAAIAAAeIgqAAIAAA6IA9AAIAAAjgAiyBpIAAhWIgth7IAoAAIAbBVIAahVIAoAAIgxB7IAABWgAmQBpIAAjRIA8AAQAcAAAPAQQAPAPAAAaIAABhQAAAZgPAPQgPAPgcAAgAlpBHIATAAQAUAAABgXIAAhfQgBgXgUAAIgTAAgAnJBpIg3h6IAAB6IgkAAIAAjRIAiAAIA0B7IAAh7IAjAAIAADRgAsnBpIAAjRIBjAAIAAAhIg8AAIAAA3IAsAAIAAAgIgsAAIAABZg");
	this.shape.setTransform(88.95,18.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// box
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0A8CC1").s().p("AtzC0IAAlnIbnAAIAAFng");
	this.shape_1.setTransform(88.4,18.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.TAG, new cjs.Rectangle(0,0,176.8,36.1), null);


(lib.LEGAL = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnCB5QAAAAABgBQAAAAABAAQAAgBAAAAQABAAAAgBIABgFIgEAAIAAgIIAIAAIAAAIQAAAEgCACQgBAEgDABgAJWBtQgGgDgDgHQgCgIAAgIQAAgIADgHQAEgHAFgDQAHgEAIAAQAIAAAGAFQAGAEACAIIgHABQgDgGgDgDQgEgCgFAAQgHAAgEADQgFADgCAFQgCAGABAFQAAAIABAFQADAGAEADQAFACAFAAQAGAAAFgDQAEgFACgHIAHADQgCAIgGAFQgGAGgJAAQgKAAgGgFgAFzBsQgGgGAAgKQAAgKAGgGQAFgGAIAAQAJAAAFAGQAFAGAAAJIAAADIgfAAQABAGADAEQADADAFAAQAFAAACgBQADgCACgFIAHABQgCAGgEAEQgFADgIABQgIgBgFgFgAGMBYQgBgFgCgDQgDgEgGAAQgEAAgDADQgEAEgBAFIAYAAIAAAAgAFKBrIAAAGIgHAAIAAg6IAHAAIAAAVQAFgGAHAAQAEAAADABQADACACADIAEAGIABAJQAAALgFAFQgGAHgGAAQgIAAgEgHgAFNBQQgEAEAAAHQAAAIADADQADAFAGAAQAEAAADgDQAEgFAAgIQAAgHgDgEQgEgEgEAAQgFAAgDAEgADYBsQgFgGgBgKQABgKAFgGQAFgGAJAAQAIAAAGAGQAEAGAAAJIAAADIgeAAQAAAGADAEQAEADAFAAQAEAAADgBQADgCABgFIAHABQgCAGgEAEQgFADgHABQgJgBgFgFgADyBYQgBgFgDgDQgDgEgFAAQgFAAgDADQgEAEAAAFIAYAAIAAAAgABBBuQgFgEgBgGIAHgBQABAEACADQADABAFAAQAFAAACgBQABgBAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBgBIgHgCIgLgEQgDgBgBgCQgCgDAAgDIACgFQABgCACgCIAFgCIAGgBQAFAAADABQAEACACADIACAFIgHABQAAgDgCgBQgCgCgFAAQgEAAgDACQAAAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIABACQABABAAAAQAAABAAAAQABAAAAAAQAAAAABABIAGACIAKACQAEACABADQACACAAADQAAAEgCADQgCADgEACQgEABgFABQgIgBgEgDgAgWBsQgGgGABgKQgBgMAHgGQAGgEAHAAQAIAAAFAGQAFAFABAKQgBAIgCAFQgCAFgFACQgDACgGABQgIgBgGgFgAgQBQQgEAEAAAIQAAAHAEAFQADADAFAAQAGAAACgDQADgFAAgIQAAgHgDgEQgCgEgGAAQgFAAgDAEgAh4BuQgEgCgCgFQgDgFAAgGQAAgHADgFQACgEAEgDQAEgDAFAAQAEAAADABQADACACADIAAgVIAGAAIAAA6IgGAAIAAgGQgEAHgIAAQgEAAgFgEgAh2BQQgDADAAAJQAAAIAEAEQADADAEAAQAFAAADgDQAEgEAAgIQAAgIgEgEQgDgEgFAAQgEAAgEAEgAjTBsQgGgGABgKQgBgMAHgGQAGgEAHAAQAIAAAGAGQAFAFABAKQgBAIgCAFQgCAFgFACQgEACgGABQgIgBgGgFgAjNBQQgEAEAAAIQAAAHAEAFQADADAFAAQAGAAADgDQADgFAAgIQAAgHgDgEQgDgEgGAAQgFAAgDAEgAj6BsQgGgGAAgKQAAgHACgFQADgFAEgDQAEgCAGAAQAHAAAEADQAEAEABAGIgGACQgBgFgDgCQgCgCgEAAQgFAAgEAEQgDAEAAAHQAAAJADAEQAEADAFAAQAEABADgDQACgDABgFIAHABQgBAHgEAEQgFAFgHAAQgJgBgEgFgAk5BuQgFgCgCgFQgDgFABgGQgBgHADgFQACgEAEgDQAEgDAGAAQADAAADABQADACABADIAAgVIAIAAIAAA6IgHAAIAAgGQgEAHgHAAQgGAAgDgEgAk4BQQgDADAAAJQAAAIAEAEQADADAFAAQAEAAADgDQADgEAAgIQAAgIgDgEQgDgEgFAAQgEAAgEAEgAmXBuQgDgDAAgGQAAgCABgDQABgDADgBIAFgDIAGAAIANgDIAAgBQAAgFgCgBQgDgDgFAAQgFAAgDACQgCACgBAEIgHgBIADgHQACgDAEgCQAFgBAFAAQAFAAADABQAEABACACIABAGIABAGIAAAJIAAAMIACAGIgHAAQgCgCAAgEIgHAFIgIACQgHgBgEgDgAmIBfIgHABIgDACIAAADQAAABAAABQAAAAAAABQAAAAABABQAAAAAAABQACACAFAAQAEAAADgCQADgBABgEQACgCAAgEIAAgEIgLAEgAnpBuQgFgEAAgGIAGgBQABAEADADQADABAEAAQAFAAACgBQABgBAAgBQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBIgGgCIgMgEQgCgBgCgCQgCgDABgDIABgFQABgCACgCIAFgCIAGgBQAFAAADABQAEACACADIACAFIgGABQgBgDgCgBQgCgCgEAAQgGAAgBACQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIABACQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABABIAGACIALACQADACABADQACACAAADQAAAEgCADQgCADgEACQgEABgFABQgIgBgEgDgApyBsQgFgGAAgKQAAgKAFgGQAFgGAKAAQAHAAAGAGQAFAGAAAJIAAADIgfAAQABAGADAEQADADAGAAQADAAADgBQADgCACgFIAHABQgCAGgEAEQgFADgHABQgKgBgFgFgApYBYQgBgFgCgDQgDgEgFAAQgGAAgCADQgEAEgBAFIAYAAIAAAAgAg7BwIgDgEIgBgIIAAgXIgFAAIAAgGIAFAAIAAgKIAHgFIAAAPIAHAAIAAAGIgHAAIAAAXIAAAFIACABIACAAIADAAIABAHIgFAAIgGgBgAqFBwIgDgEQgCgBAAgHIAAgXIgEAAIAAgGIAEAAIAAgKIAHgFIAAAPIAHAAIAAAGIgHAAIAAAXIABAFIABABIADAAIACAAIABAHIgEAAIgGgBgAKIBxIAAgIIAIAAIAAAIgAI4BxIAAg6IAIAAIAAA6gAH9BxIAAg6IAUAAIAKABQAFABAEADQAEAEACAGQACAGABAHQAAAHgCAFQgBAFgDAEIgFAEIgHAEIgJABgAIFBqIAMAAIAJgBIAFgEQADgCABgEQACgFAAgHQAAgIgDgFQgDgFgEgCIgKgBIgMAAgAHNBxIAAg6IAmAAIAAAHIgeAAIAAASIAbAAIAAAHIgbAAIAAAagAGbBxIAAgqIAGAAIAAAHIAFgHQAAAAABAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAAEACIgCAHIgGgBIgEABQgBAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAQgBAEAAAFIAAAWgAEyBxIAAgaIAAgHIgDgCQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgFAAgDADQgCADAAAHIAAAYIgIAAIAAgbQABgFgCgCQgCgDgEAAQgDAAgCACQgDABgBADIgBAJIAAAWIgHAAIAAgqIAGAAIAAAGQACgDAEgCQADgCADAAQAFAAADACQADACACAEQAEgIAIAAQAGAAADADQAEAEAAAHIAAAdgADCBxIAAgxIgRAxIgGAAIgRgxIAAAxIgHAAIAAg6IALAAIAQAyIARgyIAKAAIAAA6gABoBxIAAgIIAIAAIAAAIgAAtBxIAAgZIgBgHQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgFAAgDADQgDADAAAIIAAAXIgHAAIAAgqIAFAAIAAAGQAFgHAJAAQADAAAEABQADACABACIACAFIABAHIAAAagAgqBxIAAgqIAHAAIAAAqgAhRBxIAAgqIAGAAIAAAqgAiPBxIAAgZIgBgHQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgFAAgDADQgDADAAAIIAAAXIgHAAIAAgqIAFAAIAAAGQAFgHAJAAQADAAAEABQADACABACIACAFIABAHIAAAagAlRBxIAAgZIgBgHQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgEAAgEADQgCADAAAIIAAAXIgIAAIAAgqIAHAAIAAAGQAEgHAJAAQADAAADABQAEACACACIACAFIAAAHIAAAagAn9BxIAAgaIgBgHIgCgCQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgEAAgDADQgDADAAAHIAAAYIgHAAIAAgbQAAgFgCgCQgBgDgEAAQgDAAgCACQgDABgBADIgBAJIAAAWIgHAAIAAgqIAGAAIAAAGQACgDAEgCQACgCAFAAQAFAAACACQADACABAEQAFgIAIAAQAGAAADADQAEAEAAAHIAAAdgApJBxIAAgqIAGAAIAAAHIAFgHQAAAAABAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAADACIgBAHIgGgBIgEABQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQgCAEAAAFIAAAWgAgqA/IAAgIIAHAAIAAAIgAhRA/IAAgIIAGAAIAAAIgAkmAnIABgGIAEABIADgBQABgCAAgGIAAgrIAIAAIAAArQAAAIgCADQgDAEgGAAIgGgBgAD8AnIAAg5IAGAAIAAAGQADgDACgCQADgBAEgBQAFABAFACQADADACAFQADAFAAAFQAAAGgDAGQgCAFgEACQgEADgFAAQgEAAgDgBQgCgCgCgDIAAAVgAEGgJQgEAEAAAHQAAAIAEAFQADADAEAAQAFAAAEgEQADgEAAgIQAAgHgDgEQgEgEgEAAQgFAAgDAEgADQAnIAAg5IAGAAIAAAGQACgDADgCQADgBAEgBQAGABAEACQADADADAFQACAFAAAFQAAAGgCAGQgDAFgEACQgFADgEAAQgEAAgDgBQgDgCgBgDIAAAVgADagJQgEAEAAAHQAAAIAEAFQADADAEAAQAFAAAEgEQACgEAAgIQAAgHgCgEQgEgEgEAAQgFAAgDAEgAHVAgQABgBAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgFIgDAAIAAgIIAIAAIAAAIQgBAFgBACQgBADgEACgAGXAUQgDgDAAgFQAAgDACgCQAAgDADgCIAFgCIAGAAIANgCIAAgCQAAgEgCgCQgDgCgFAAQgFAAgCABQgDACgBAFIgHgCQABgEACgDQACgCAFgCQAEgBAFgBQAFABAEABQADABABACIADAFIAAAGIAAAJIABAMIABAFIgHAAQgCgCABgDIgIAFIgIABQgHAAgEgEgAGmAFIgHABIgCACIgCAEQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQACACAEAAQAEAAADgCQADgBACgDQABgCAAgFIAAgDIgLADgAFFASQgFgFgBgLQABgKAGgGQAFgEAIgBQAJABAFAFQAGAGAAAIQAAAIgDAGQgDAEgEADQgEACgGAAQgIAAgGgGgAFKgJQgDAEAAAHQAAAIADAEQAEAEAFAAQAFAAAEgEQADgEABgIQgBgHgDgEQgEgDgFAAQgFAAgEADgAClAUQgEgDABgFQAAgDABgCQABgDACgCIAGgCIAFAAIAOgCIAAgCQAAgEgCgCQgEgCgEAAQgFAAgDABQgCACgBAFIgHgCIACgHQADgCAEgCQAEgBAGgBQAEABAEABQAEABABACIACAFIABAGIAAAJIAAAMIACAFIgIAAQgBgCAAgDIgIAFIgIABQgGAAgEgEgACzAFIgGABIgDACIgBAEQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQACACAEAAQAFAAACgCQADgBACgDQABgCABgFIAAgDIgMADgABBAVQgEgCgDgFQgDgGABgGQgBgFADgFQACgFAEgDQAEgCAGgBQADABADABQADABABAEIAAgWIAIAAIAAA5IgHAAIAAgFQgEAGgHAAQgFAAgEgDgABCgJQgDAEAAAHQAAAJADADQAEAEAFAAQAEAAADgDQAEgFgBgHQABgIgEgEQgDgDgFAAQgEgBgEAEgAASASQgGgFAAgLQAAgJAGgFQAFgHAIAAQAJABAFAFQAFAGAAAJIAAACIgfAAQABAHADAEQAEADAEAAQAFAAACgCQADgCABgFIAIABQgCAHgEADQgFAEgIAAQgIAAgFgGgAArgBQAAgFgDgDQgEgDgFAAQgEAAgEACQgDAEAAAFIAXAAIAAAAgAgwASQgGgFABgLQAAgGACgFQACgEAFgDQAEgCAGgBQAGABAEADQAFADABAGIgGACQgCgEgCgCQgCgCgEAAQgFgBgEAEQgDAEAAAHQAAAIADAFQAEADAFAAQADAAAEgCQACgDABgFIAHAAQgCAIgEAEQgFAEgGAAQgJAAgFgGgAhyASQgGgFAAgLQAAgKAGgGQAGgEAHgBQAJABAGAFQAFAGAAAIQAAAIgDAGQgCAEgEADQgFACgGAAQgIAAgFgGgAhtgJQgDAEgBAHQABAIADAEQADAEAFAAQAGAAADgEQAEgEAAgIQAAgHgEgEQgDgDgGAAQgFAAgDADgAjcASQgGgFABgLQAAgGACgFQACgEAFgDQAEgCAGgBQAHABAEADQAEADABAGIgGACQgBgEgDgCQgDgCgDAAQgGgBgDAEQgDAEAAAHQAAAIADAFQADADAGAAQADAAADgCQADgDABgFIAHAAQgBAIgFAEQgFAEgGAAQgJAAgFgGgAkIASQgGgFABgLQgBgJAGgFQAFgHAJAAQAIABAFAFQAGAGAAAJIAAACIggAAQABAHAEAEQADADAFAAQAEAAADgCQACgCACgFIAIABQgCAHgFADQgFAEgHAAQgJAAgFgGgAjvgBQAAgFgCgDQgEgDgFAAQgFAAgDACQgEAEAAAFIAXAAIAAAAgAlCASIAAAFIgHAAIAAg5IAIAAIAAAVQAEgFAGgBQAEABAEABQADABADAEIADAGIABAHQAAALgFAGQgFAGgIAAQgHAAgEgGgAk/gJQgEAEABAHQAAAHABAEQAEAFAGAAQAEAAAEgEQADgEAAgIQAAgHgDgEQgEgEgEABQgFAAgDADgAluAXIgFgEIgCgFIAAgHIAAgZIAHAAIAAAXIAAAHQABACACACQACACAEAAQADAAADgCQADgCAAgCIABgIIAAgWIAIAAIAAApIgHAAIAAgGQgFAHgHAAQgFAAgDgBgAmaAUQgEgDgCgHIAHgBQABAFADACQADACAEAAQAFAAACgCQABgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgHgCIgLgEQgDgBgBgCQgBgCAAgEIABgEQABgDACgCIAFgCIAGgBQAFABADABQAEACACACIACAGIgHABQAAgDgCgCQgDgBgEAAQgEAAgCABQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAIABADQABAAAAABQAAAAAAAAQABAAAAABQAAAAABAAIAGACIALACQACACACACQACACAAAEQAAADgCADQgCAEgEACQgEABgFAAQgIAAgEgEgAnYAUQgFgDAAgHIAGgBQABAFADACQADACAEAAQAFAAACgCQABgBAAAAQABgBAAAAQAAgBAAAAQABgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgGgCIgMgEQgDgBgBgCQgBgCAAgEIABgEQABgDACgCIAFgCIAGgBQAFABADABQAEACACACIACAGIgHABQAAgDgCgCQgDgBgEAAQgEAAgCABQgBAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAIACADQAAAAAAABQAAAAAAAAQABAAAAABQAAAAABAAIAGACIALACQADACABACQACACAAAEQAAADgCADQgCAEgEACQgEABgFAAQgIAAgEgEgAoyAUQgDgDAAgFQAAgDABgCQACgDACgCIAFgCIAGAAIANgCIAAgCQAAgEgCgCQgDgCgFAAQgFAAgDABQgCACgBAFIgHgCIADgHQADgCADgCQAEgBAGgBQAFABADABQAEABACACIACAFIAAAGIAAAJIABAMIABAFIgHAAQgBgCgBgDIgHAFIgIABQgHAAgEgEgAojAFIgHABIgCACIgBAEQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQACACAEAAQAEAAADgCQADgBACgDQABgCAAgFIAAgDIgLADgApcASQgFgFAAgLQAAgKAGgGQAGgEAHgBQAJABAFAFQAGAGgBAIQABAIgDAGQgDAEgEADQgFACgFAAQgJAAgFgGgApXgJQgDAEAAAHQAAAIADAEQAEAEAFAAQAFAAAEgEQADgEAAgIQAAgHgDgEQgEgDgFAAQgFAAgEADgAB9AXIgDgEIgBgIIAAgXIgFAAIAAgGIAFAAIAAgKIAHgEIAAAOIAHAAIAAAGIgHAAIAAAXIAAAEIABABIADABIADgBIABAHIgFABIgGgBgAiGAXIgDgEIgBgIIAAgXIgFAAIAAgGIAFAAIAAgKIAHgEIAAAOIAHAAIAAAGIgHAAIAAAXIAAAEIABABIADABIADgBIABAHIgFABIgGgBgAiyAXIgDgEIgBgIIAAgXIgFAAIAAgGIAFAAIAAgKIAHgEIAAAOIAHAAIAAAGIgHAAIAAAXIAAAEIABABIADABIADgBIABAHIgFABIgGgBgAHCAXIAAg5IAHAAIAAA5gAF6AXIgQgpIAIAAIALAhIAMghIAHAAIgQApgAEoAXIAAgpIAGAAIAAAHIAFgGQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABgBQADABAEACIgCAGIgGgBIgDABQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQgCAEAAADIAAAWgABmAXIAAgpIAIAAIAAApgAgMAXIAAgpIAHAAIAAAHIAFgGQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQAEABADACIgCAGIgGgBIgCABQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQgBAEgBADIAAAWgAnsAXIAAgYIgBgHQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBAAgBAAQgEAAgEACQgCAEAAAGIAAAXIgIAAIAAgpIAHAAIAAAHQAEgIAJAAQAEABADABQADABABADIADAEIAAAIIAAAYgAqKAXIAAg5IAHAAIAAAyIAcAAIAAAHgABmgZIAAgJIAIAAIAAAJgAkdgZIAAgJIAIAAIAAAJgAhlg0QgEgDAAgHIAHABQAAABAAAAQAAABAAABQABAAAAABQAAAAABABQADABAEAAQAFAAADgBQACgCABgEIAAgJQgEAFgHABQgIAAgFgHQgFgGAAgJQAAgFACgGQADgEAEgDQAEgDAFAAQAHAAAFAGIAAgFIAHAAIAAAkQAAAJgCAFQgDAEgDACQgFADgGAAQgHAAgFgEgAhghjQgDAEAAAIQAAAIADAEQADADAFAAQAEAAAEgDQADgEAAgIQAAgHgDgEQgEgEgEAAQgFAAgDADgAowg0QgEgDAAgHIAHABQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQADABAFAAQAEAAADgBQACgCABgEIABgJQgFAFgGABQgJAAgFgHQgEgGAAgJQAAgFABgGQADgEAEgDQAEgDAGAAQAHAAAEAGIAAgFIAHAAIAAAkQAAAJgCAFQgCAEgEACQgFADgFAAQgIAAgFgEgAorhjQgDAEAAAIQAAAIADAEQAEADAEAAQAFAAAEgDQACgEAAgIQAAgHgDgEQgDgEgFAAQgEAAgEADgAFlgxIAAgVQgBACgDACIgGACQgHAAgGgHQgFgFAAgLQAAgGACgFQACgFAEgDQAFgCAEAAQAIAAAFAHIAAgGIAGAAIAAA6gAFThjQgDAEAAAIQAAAIADAFQAEADAEAAQAFABADgEQAEgEAAgHQAAgJgEgEQgEgFgEABQgFAAgDADgAIChDQgFgDgCgFQgDgFABgGQgBgGADgGQACgEAEgDQAEgDAGAAQADAAADABQADACABADIAAgVIAIAAIAAA6IgHAAIAAgGQgEAHgHAAQgGAAgDgDgAIDhjQgDAEAAAJQAAAIAEAEQADADAFAAQAEABADgEQADgEAAgHQAAgJgDgEQgDgEgFAAQgEAAgEADgAHThGQgGgGAAgKQAAgKAGgGQAEgGAJAAQAJAAAFAGQAFAGAAAJIAAADIgfAAQAAAGAEAEQAEAEAEgBQAEAAAEgBQACgDABgEIAIABQgCAGgFAEQgEADgIABQgJgBgEgFgAHshaQAAgGgDgCQgEgEgFAAQgFAAgDADQgDADAAAGIAXAAIAAAAgAF+hCIgEgEIgDgEIAAgHIAAgaIAHAAIAAAXIAAAIQABACADACQACACACgBQAEABADgCQACgCABgCIABgJIAAgWIAIAAIAAAqIgHAAIAAgHQgEAIgIAAQgFgBgDgBgAEjhGQgGgGAAgKQAAgKAGgGQAEgGAKAAQAHAAAGAGQAFAGAAAJIAAADIgfAAQABAGADAEQADAEAGgBQAEAAACgBQADgDACgEIAHABQgCAGgEAEQgFADgHABQgKgBgEgFgAE8haQgBgGgCgCQgDgEgFAAQgGAAgCADQgEADgBAGIAYAAIAAAAgACIhCIgFgEIgCgEIgBgHIAAgaIAIAAIAAAXIAAAIQAAACADACQACACADgBQADABADgCQADgCABgCIABgJIAAgWIAIAAIAAAqIgHAAIAAgHQgFAIgIAAQgEgBgDgBgABXhGQgFgGAAgKQAAgMAHgFQAFgFAHAAQAJAAAGAGQAFAFAAAKQAAAIgCAFQgDAFgFACQgEACgGABQgIgBgGgFgABdhiQgEAEABAIQgBAHAEAFQAEADAEAAQAGAAADgDQAEgFAAgIQAAgHgEgEQgDgEgGAAQgEAAgEAEgAAwhGQgGgGAAgKQAAgHADgFQACgFAEgDQAFgCAGAAQAGAAAFADQAEAEABAGIgGACQgBgFgDgCQgDgCgDAAQgFAAgEADQgDAEAAAIQAAAJADAEQADAEAGgBQADABADgDQADgDABgFIAHABQgBAHgFAEQgFAFgGAAQgJgBgFgFgAAIhGQgFgGgBgKQABgHACgFQACgFAEgDQAFgCAFAAQAIAAADADQAFAEABAGIgHACQAAgFgDgCQgDgCgDAAQgGAAgDADQgDAEAAAIQAAAJADAEQAEAEAEgBQAEABAEgDQACgDABgFIAHABQgCAHgEAEQgEAFgIAAQgIgBgFgFgAglhEQgDgDgBgFQABgDABgDQABgDADgBIAEgDIAHgBIAMgCIAAgBQAAgFgCgCQgCgCgGAAQgEAAgDACQgCACgCAEIgHgBQABgEADgDQACgDAEgCQAEgBAFAAQAGAAADABQADABACADIACAEIAAAHIAAAJIABAMIABAGIgGAAQgCgDAAgDIgHAFIgIACQgIgBgDgDgAgXhTIgHABIgCACIgBAEQAAAAAAABQAAAAAAABQABAAAAABQABABAAAAQACACAFAAQADAAAEgCQADgCABgCQABgDAAgEIAAgEIgLAEgAjyhGQgGgGAAgKQAAgHACgFQACgFAFgDQAEgCAGAAQAHAAAEADQAEAEABAGIgGACQgBgFgCgCQgDgCgEAAQgFAAgEADQgCAEAAAIQAAAJACAEQAEAEAFgBQAEABADgDQADgDAAgFIAHABQgBAHgFAEQgEAFgHAAQgJgBgEgFgAkehGQgGgGAAgKQAAgKAGgGQAFgGAIAAQAJAAAFAGQAFAGAAAJIAAADIgfAAQAAAGAEAEQADAEAFgBQAFAAACgBQADgDACgEIAHABQgCAGgEAEQgFADgIABQgIgBgFgFgAkFhaQgBgGgCgCQgDgEgGAAQgEAAgEADQgDADgBAGIAYAAIAAAAgAlzhGQgFgGAAgKQAAgHACgFQACgFAFgDQAFgCAFAAQAHAAAEADQAFAEABAGIgHACQgBgFgCgCQgDgCgDAAQgGAAgEADQgCAEAAAIQAAAJACAEQAEAEAFgBQAEABADgDQACgDABgFIAIABQgCAHgFAEQgEAFgHAAQgIgBgGgFgAm1hGQgFgGAAgKQAAgKAFgGQAFgGAKAAQAHAAAGAGQAFAGAAAJIAAADIgfAAQABAGADAEQADAEAGgBQADAAADgBQADgDACgEIAHABQgCAGgFAEQgEADgHABQgKgBgFgFgAmbhaQgBgGgCgCQgDgEgFAAQgGAAgCADQgEADgBAGIAYAAIAAAAgAnuhHIAAAGIgHAAIAAg6IAHAAIAAAVQAEgGAHAAQAEAAAEABQADACACADIAEAGIABAJQAAALgGAFQgFAHgHAAQgHAAgEgHgAnshiQgDAEAAAHQAAAIACADQAEAGAFgBQAFAAADgDQADgFAAgIQAAgIgCgEQgEgDgEAAQgFAAgEAEgADehCIgDgEQgBgBAAgHIAAgXIgFAAIAAgGIAFAAIAAgLIAHgDIAAAOIAHAAIAAAGIgHAAIAAAXIABAFIABABIACAAIADAAIABAHIgFAAIgGgBgAIphBIAAgIIAIAAIAAAIgAG0hBIAAgqIAHAAIAAAHIAEgHQABAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAEAAADACIgCAHIgFgBIgFABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgBAFgBAEIAAAWgAGjhBIAAgqIAHAAIAAAqgAEFhBIAAgqIAGAAIAAAHIAFgHQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQADAAAEACIgCAHIgGgBIgDABQgBAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQgCAFAAAEIAAAWgADIhBIAAgaIgBgGQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgEAAgEADQgDADAAAIIAAAXIgHAAIAAgqIAGAAIAAAGQAEgHAJAAQAEAAADABQAEACABACIACAFIABAHIAAAagAh6hBIAAgaIgBgGQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgFAAgDADQgDADAAAIIAAAXIgHAAIAAgqIAGAAIAAAGQAFgHAIAAQAEAAADABQAEACABACIACAFIABAHIAAAagAimhBIAAgqIAHAAIAAAqgAi0hBIgOgWIgEAFIAAARIgHAAIAAg6IAHAAIAAAhIAQgRIAJAAIgQAQIASAagAkzhBIAAgbQAAgFgCgDQgCgCgEAAQgEAAgCACQgDACgCACIgBAIIAAAXIgGAAIAAg6IAGAAIAAAVQAFgGAIAAQAEAAAEACQADACABADQACADAAAGIAAAbgAnJhBIAAg6IAHAAIAAA6gAoHhBIAAgqIAIAAIAAAqgApEhBIAAgqIAHAAIAAAqgApWhBIAAg6IAHAAIAAA6gAqKhBIAAg6IApAAIAAAHIghAAIAAARIAgAAIAAAIIggAAIAAATIAjAAIAAAHgAGjhzIAAgIIAHAAIAAAIgAimhzIAAgIIAHAAIAAAIgAoHhzIAAgIIAIAAIAAAIgApEhzIAAgIIAHAAIAAAIg");
	this.shape.setTransform(67.7,15.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.LEGAL, new cjs.Rectangle(2.2,3.5,131.10000000000002,24.8), null);


(lib.HEAD = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_24();
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD, new cjs.Rectangle(0,0,151.5,160), null);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#04103D").s().p("AEzCsIAAgDQAKgBAJgJQAKgIAIgRIgcg8QgCgGgCgCQgCgBgFAAIAAgFIAoAAIAAAFIgHAAQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAADIACADIAQAoIAQgnIACgEIAAgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAIgJgBIAAgFIAcAAIAAAFQgGAAgCABQgBACgDAHIgZA4IgNAcQgHAMgEADgAGOCJQgDgEAAgFQAAgFADgDQAEgEAEAAQAFAAAEAEQADADAAAFQAAAFgDAEQgEADgFAAQgEAAgEgDgAEYCJQgEgEgDgGQgDAFgGAEQgGAEgHAAQgHAAgHgFQgFgFAAgIQAAgJAHgEQAGgGALgDIARgHIAAgFQAAgIgDgFQgFgHgIAAQgGABgGAEQgFAEgDAIIgEgCQADgLAJgGQAIgHAMAAQANAAAHAIQAIAHAAAMIAAAmQAAAEABACQAAAAABAAQABABAAAAQABAAAAAAQABAAAAAAIAEAAIADgDIACACQgDAEgEADQgEADgGAAQgFAAgFgDgAEFBnQgFACgEADQgCADAAAHQAAAFACAEQAEADAFABQAEgBADgBIAFgFIAAgagACYCCQgKgLAAgQQAAgVAMgMQAMgLAOAAQAGAAADABQAFACADADIAAgfQAAgGgCgCQgCgBgIAAIAAgEIAfAAIAABnQAAAHACABQACACAGAAIAAAEIgdAAIAAgKQgDAFgGADQgGAEgIAAQgNAAgJgKgACpBJQgIAIAAARQABAOAFAKQAGAJAKAAQAFAAADgBIAGgGIAAg4IgGgCIgGgBQgKgBgGAJgABGCBQgMgMABgRQgBgTAMgLQAMgLAPAAQAPAAAMALQALALAAATQAAARgLAMQgMALgPAAQgPAAgMgLgABTBJQgFAIAAATQAAARAFAJQAGAJAIAAQAIAAAFgJQAGgJAAgRQAAgTgGgIQgFgJgIAAQgIAAgGAJgAAQCGQgGgHAAgJIAAg0IgJAAIAAgCQAHgFAIgHQAHgHAEgGIACAAIAAAWIAZgBIgBAHIgYAAIAAAwQAAAHADAEQADAEAGABQAEAAADgCIAGgHIACADQgEAHgGAEQgHAEgHAAQgJAAgHgGgAhvB9QgSgOAAgaQAAgZAQgRQARgQAXAAQALAAAHADQAGAEADgBIACgBIACgDIADAAIACAgIgEAAQgDgNgHgHQgIgJgNAAQgQAAgKANQgKAMAAAUQAAAZANAOQAOAOARABQAHgBAGgCQAHgCAHgHIADACQgGAIgKAFQgJAGgOAAQgVAAgRgPgAjoB7QgQgQAAgXQAAgYAQgRQAQgQAWAAQAVAAARAQQAQARAAAYQAAAXgQAQQgRARgVAAQgWAAgQgRgAjZAvQgJAOAAAXQAAAWAJAPQAJANAOAAQAOAAAJgNQAJgPAAgWQAAgXgJgOQgJgOgOgBQgOABgJAOgAnvCJQgFgEgCgGQgDAFgGAEQgGAEgHAAQgHAAgHgFQgFgFAAgIQAAgJAGgEQAHgGALgDIARgHIAAgFQAAgIgDgFQgFgHgJAAQgGABgFAEQgFAEgDAIIgDgCQACgLAJgGQAIgHAMAAQAMAAAIAIQAIAHgBAMIAAAmQAAAEACACQAAAAABAAQABABAAAAQABAAAAAAQABAAABAAIACAAIAEgDIACACQgDAEgEADQgEADgGAAQgFAAgFgDgAoCBnQgFACgDADQgDADAAAHQAAAFADAEQADADAFABQAEgBADgBIAFgFIAAgagArECGQgGgHAAgJIABg0IgKAAIAAgCQAIgFAHgHQAHgHAFgGIABAAIAAAWIAZgBIgCAHIgXAAIAAAwQAAAHADAEQADAEAGABQAEAAADgCIAGgHIADADQgFAHgGAEQgGAEgIAAQgKAAgGgGgAsoCMIgTgzIgUAzIgBAAIgchCQgDgHgCgBQgCgBgFAAIAAgFIAnAAIAAAFIgHAAQgBAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABIARAtIAMgeIgEgJQgCgHgCgBQgDgBgFAAIAAgFIAmAAIAAAFIgHAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAABAAAAIAAACIAPArIAOgqIABgCQgBgDgDgBIgIAAIAAgFIAdAAIAAAFQgGAAgCABQgCABgDAIIgZBBgAlXCKIAAgEQAIAAACgCQADgBAAgHIAAhSQAAgGgDgCQgCgBgIAAIAAgEIAvAAIAAAEQgIAAgCABQgDACAAAGIAABSQAAAFACACQABACAGAAIAKAAQANAAAGgFQAGgFAFgTIADAAIgDAigAm2CKIAAgEQAHAAADgCQAEgBAAgHIAAhSQAAgGgEgCQgDgBgHAAIAAgEIAsAAQASAAAOAHQANAHAAAQQABAPgNAIQgNAIgQAAIgPgCIAAAkQAAAHADABQAEACAKAAIAAAEgAmVBUIAGABIAFAAQAKAAAIgHQAHgGAAgOQAAgOgIgEQgIgGgNAAIgHAAgApqCKIAAgEQAGAAACgCQACgBAAgHIAAgkQAAgJgEgFQgDgFgIAAQgEAAgEACQgEADgDAFIAAAtQAAAHACABQACACAGAAIAAAEIgmAAIAAgEQAFAAADgCQABgBAAgHIAAhaQAAgGgCgCQgCgBgHAAIAAgEIAeAAIAAA2QADgFAHgGQAHgFAIAAQAMAAAHAIQAFAHAAALIAAAnQAAAHACABQACACAGAAIAAAEgAr9CKIAAgEQAFAAADgCQACgBAAgHIAAgyQAAgHgCgBQgDgBgFAAIAAgFIAcAAIAABAQAAAHACABQACACAGAAIAAAEgArzArQgDgDAAgFQAAgEADgEQAEgDAEAAQAFAAAEADQACAEAAAEQAAAFgCADQgEADgFAAQgEAAgEgDgAkLgWIAAgCQAKgCAJgIQAKgJAIgQIgcg9QgCgGgCgCQgCgBgFgBIAAgDIAoAAIAAADIgHABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAADIACADIAQApIAQgpIACgCIAAgDQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAgBgBIgIgBIAAgDIAcAAIAAADQgFABgDABQgBACgDAGIgZA5IgNAcQgHALgDAEgAMlgWIAAgDQAGAAACgCQACgBAAgIIAAhUQAAgGgCgCQgCgBgGgBIAAgDIAdAAIAAALQACgEAHgFQAHgEAHAAQAOAAAJALQAJAKAAARQAAATgLAMQgMAMgOAAQgGAAgEgCQgFgBgDgDIAAAYQAAAIACABQADACAIAAIAAADgANIh8QgEACgCADIAAA2QACADAEABIAHABQAIAAAHgHQAIgJAAgSQAAgNgGgKQgFgKgLAAQgEAAgEADgABWgWIAAgDQAFAAACgCQACgBAAgIIAAhUQAAgGgCgCQgCgBgFgBIAAgDIAdAAIAAALQACgEAHgFQAGgEAIAAQANAAAKALQAJAKAAARQAAATgMAMQgMAMgOAAQgFAAgFgCQgEgBgDgDIAAAYQgBAIADABQACACAJAAIAAADgAB4h8QgDACgCADIAAA2QACADADABIAHABQAIAAAIgHQAHgJAAgSQAAgNgGgKQgEgKgLAAQgEAAgFADgAJug5QgEgEgCABIgCABIgCADIgCAAIgBgbIADAAQABAKAHAHQAHAGAJABQAGAAAEgEQADgCAAgHQAAgEgCgCIgIgGIgOgHQgGgDgFgFQgEgFAAgIQAAgKAIgHQAHgGALAAQAHAAAEACIAGACIADgBIAAgDIADAAIABAYIgDAAQgCgJgFgFQgGgFgHAAQgFAAgEACQgDAEAAAFQAAAEADADIAIAFIALAGQAHAEAFAFQAFAFAAAJQAAAKgIAHQgIAHgLAAQgJAAgGgDgAHehBQgLgMAAgRQAAgRALgMQAMgMAOAAQAPAAAIAKQAHAKAAALIgxAAIAAACQAAARAJAKQAHAKANAAQAGAAAFgCQAFgBADgGIADACQgGAJgIAFQgIAEgJAAQgPAAgMgLgAIGhtQgBgJgEgGQgDgGgHAAQgHgBgFAHQgEAFgBAKIAgAAIAAAAgAFNg8QgGgGAAgKIAAg0IgJAAIAAgCQAHgFAIgHQAHgGAEgHIACAAIAAAWIAZgBIgCAGIgXAAIAAAyQAAAGADAEQADAFAGgBQAEAAADgCIAGgGIADADQgFAHgGAEQgHAEgHAAQgKAAgGgGgADhg5QgFgDgCgHQgDAFgGAEQgGAEgHAAQgHAAgHgFQgFgEAAgJQAAgJAGgEQAHgFALgEIARgHIAAgFQAAgIgDgGQgEgFgKgBQgFAAgGAFQgFAEgDAHIgDgBQACgLAJgGQAIgHAMAAQANAAAHAHQAIAIgBAMIAAAmQAAADACACQAAABABAAQABABAAAAQABAAAAAAQABAAAAAAIADgBIAEgDIACADQgDAEgEADQgEADgGAAQgFAAgFgDgADOhcQgFACgEAEQgCAEAAAGQAAAFACAEQAEAEAFgBQADAAAEgBIAFgFIAAgagAhUg+QgHgIABgKIAAgoQAAgHgCgBQgCgBgGgBIAAgDIAcAAIAAAyQABAJADAGQAEAEAHAAQAEAAADgDQAFgBABgGIAAguQAAgHgBgBQgDgBgGgBIAAgDIAeAAIAABAQAAAGABACQADABAFAAIAAAEIgdAAIAAgNQgCAGgHAEQgFAFgJAAQgMAAgFgIgAiqhCQgLgLAAgRQAAgSALgMQAMgLAOAAQAPAAAMALQAMAMAAASQAAARgMALQgMAMgPAAQgOAAgMgMgAich5QgGAJAAASQAAARAGAJQAEAJAIAAQAJAAAGgJQAEgJAAgRQAAgSgEgJQgGgKgJABQgIgBgEAKgAn5g8QgGgGAAgKIAAg0IgJAAIAAgCQAIgFAHgHQAHgGAEgHIACAAIAAAWIAZgBIgBAGIgYAAIAAAyQAAAGADAEQADAFAGgBQAEAAADgCIAGgGIACADQgEAHgGAEQgHAEgHAAQgJAAgHgGgAo4g5QgFgEgCABIgBABIgCADIgDAAIgBgbIAEAAQAAAKAIAHQAGAGAJABQAHAAADgEQAEgCAAgHQAAgEgDgCIgIgGIgOgHQgGgDgEgFQgFgFAAgIQABgKAHgHQAIgGAKAAQAHAAAFACIAFACIADgBIABgDIADAAIABAYIgDAAQgCgJgFgFQgHgFgHAAQgFAAgEACQgDAEAAAFQAAAEADADIAIAFIAMAGQAHAEAFAFQAEAFAAAJQAAAKgHAHQgIAHgMAAQgJAAgFgDgAqGhBQgLgMAAgRQAAgRALgMQAMgMANAAQAQAAAIAKQAHAKAAALIgxAAIAAACQAAARAJAKQAHAKANAAQAGAAAFgCQAFgBADgGIADACQgGAJgIAFQgIAEgJAAQgPAAgMgLgApehtQgBgJgEgGQgDgGgHAAQgHgBgFAHQgEAFgCAKIAhAAIAAAAgAq+g2IgfhCQgCgGgCgCQgDgBgFgBIAAgDIAoAAIAAADIgHABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIABAGIASApIAPgpIACgGQAAAAAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAIgIgBIAAgDIAdAAIAAADQgHABgBABQgDACgDAGIgcBCgAL7g4IAAgEQAGAAACgBQACgCAAgGIAAgzQAAgHgCgBQgCgBgGgBIAAgDIAcAAIAABAQAAAGACACQADABAFAAIAAAEgALPg4IAAgEQAGAAACgBQACgCAAgGIAAglQAAgKgEgEQgEgFgHAAQgEAAgEADQgEADgCAEIAAAuQAAAGABACQACABAHAAIAAAEIgnAAIAAgEQAFAAACgBQADgCAAgGIAAhaQAAgHgDgBQgCgCgIAAIAAgEIAgAAIAAA2QADgGAGgFQAGgFAJAAQAMAAAHAHQAFAJAAAKIAAAoQAAAGACACQACABAGAAIAAAEgAIdg4IAAgEQAGAAACgBQACgCAAgGIAAgzQAAgHgCgBQgCgBgGgBIAAgDIAdAAIAAAQIALgNQAEgFAGAAQAEAAADADIAFAEIgHARIAAAAQgCgFgEgDQgEgCgEAAQgDAAgDABIgGAIIAAArQAAAGADACQACABAJAAIAAAEgAGog4IAAgEQAGAAACgBQACgCgBgGIAAglQABgKgEgEQgEgFgHAAQgEAAgEADIgHAHIAAAuQAAAGACACQADABAFAAIAAAEIgmAAIAAgEQAGAAACgBQACgCAAgGIAAgzQAAgHgCgBQgCgBgGgBIAAgDIAcAAIAAANQADgEAHgGQAHgFAIAAQAMAAAGAHQAGAJAAAKIAAAoQAAAGACACQACABAGAAIAAAEgAD8g4IAAgEQAHAAACgBQABgCAAgGIAAgzQAAgHgBgBQgCgBgHgBIAAgDIAdAAIAAAQIALgNQAEgFAGAAQAEAAADADIAGAEIgHARIgBAAQgCgFgEgDQgDgCgEAAQgEAAgDABIgGAIIAAArQAAAGADACQADABAIAAIAAAEgAgJg4IAAgEQAFAAADgBQABgCAAgGIAAgzQAAgHgBgBQgDgBgFgBIAAgDIAbAAIAAAQIALgNQAEgFAGAAQAEAAADADIAGAEIgHARIAAAAQgDgFgEgDQgDgCgFAAQgDAAgCABIgHAIIAAArQABAGACACQACABAJAAIAAAEgAlUg4IAAgEQAGAAACgBQACgCgBgGIAAglQABgKgEgEQgEgFgHAAQgEAAgEADIgHAHIAAAuQAAAGACACQADABAFAAIAAAEIgmAAIAAgEQAGAAACgBQACgCAAgGIAAgzQAAgHgCgBQgCgBgGgBIAAgDIAcAAIAAANQADgEAGgGQAIgFAIAAQAMAAAGAHQAGAJAAAKIAAAoQAAAGACACQACABAGAAIAAAEgAmwg4IAAgEQAGAAACgBQACgCAAgGIAAgzQAAgHgCgBQgCgBgGgBIAAgDIAdAAIAABAQAAAGACACQACABAGAAIAAAEgAsRg4IAAgEQAGAAACgBQABgCABgGIAAglQgBgKgDgEQgEgFgHAAQgEAAgFADIgFAHIAAAuQAAAGACACQABABAHAAIAAAEIgoAAIAAgEQAHAAABgBQACgCAAgGIAAgzQAAgHgCgBQgBgBgHgBIAAgDIAeAAIAAANQACgEAHgGQAGgFAJAAQAMAAAGAHQAGAJAAAKIAAAoQAAAGACACQACABAGAAIAAAEgAt2g4IAAgEQAHAAAEgBQACgCAAgGIAAhSQAAgHgCgBQgEgCgHAAIAAgEIAvAAIAAAEQgIAAgCACQgEABAAAHIAABSQAAAGAEACQACABAIAAIAAAEgAMGiXQgEgDAAgFQAAgEAEgEQADgDAFAAQAEAAAEADQACAEAAAEQAAAFgCADQgEADgEAAQgFAAgDgDgAmliXQgEgDABgFQgBgEAEgEQADgDAFAAQAEAAAEADQADAEAAAEQAAAFgDADQgEADgEAAQgFAAgDgDg");
	this.shape.setTransform(90.95,22.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(2.1,5.6,177.8,34.8), null);


// stage content:
(lib.SB_wedding_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,88];
	// timeline functions:
	this.frame_0 = function() {
		//if(!this.alreadyyExecuted){
		//this.alreadyyExecuted=true;
		//	this.clickthru_btn.on("click", function(evt){
		//  window.open(clickTag, "_blank");
		//});
		//} else {
		//gotoAndPlay(2);
		//}
	}
	this.frame_88 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(88).call(this.frame_88).wait(1));

	// HEAD
	this.instance = new lib.HEAD();
	this.instance.setTransform(119.8,174.9,1,1,0,0,0,113.5,148.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({y:154.9,alpha:1},10,cjs.Ease.quadOut).wait(78));

	// TAG
	this.instance_1 = new lib.TAG();
	this.instance_1.setTransform(81,195.8,0.6868,0.6868,0,0,0,104,18.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(71).to({_off:false},0).to({y:175.8,alpha:1},10,cjs.Ease.quadOut).wait(8));

	// CTA
	this.instance_2 = new lib.CTA();
	this.instance_2.setTransform(76.4,226.9,0.6823,0.6823,0,0,0,99.7,25.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(74).to({_off:false},0).to({y:206.9,alpha:1},10,cjs.Ease.quadOut).wait(5));

	// LEGAL
	this.instance_3 = new lib.LEGAL();
	this.instance_3.setTransform(117.8,595.3,1,1,0,0,0,102.9,11);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(77).to({_off:false},0).to({y:575.3,alpha:1},10,cjs.Ease.quadOut).wait(2));

	// logo bmp
	this.instance_4 = new lib.logowhite2x();
	this.instance_4.setTransform(88,505);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(89));

	// BKGD
	this.instance_5 = new lib.wedding_160x6001x();

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(89));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(80,300,80,312.6);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 160,
	height: 600,
	fps: 36,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/SB_wedding_160x600_atlas_1.png?1663364175985", id:"SB_wedding_160x600_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;